### ISSUE TITLE
Update to 0.8.2

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.OCRFeeder#11]
There's now a 0.8.2 release available:

https://www.joaquimrocha.com/2020/01/26/ocrfeeder-0-8-2-released/

thanks to @scx for the hard work in getting all this stuff upstream.

**Comment by scx** [comment]
I'm working on it, but I still have to fix a minor issue with `ghostscript`.
Anyway, the update to `0.8.2` should appear today.
